### ISSUE TITLE
[bug] Missing 'click' dependency on PyPI 

### ISSUE THREAD

**Issue by breznak** [rahiel/firectl#10]
```
# pip install firectl
Collecting firectl
  Using cached firectl-1.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-Vb1jZr/firectl/setup.py", line 4, in <module>
        import firectl
      File "/tmp/pip-build-Vb1jZr/firectl/firectl.py", line 21, in <module>
        import click
    ImportError: No module named click

```
Ubuntu 16.04
Similar to #6  
`dpkg and apt install -f` and with firectl being suggested for removal. Dpkg reports missing `python3-click` dep.

**Comment by rahiel** [comment]
Hi,

The installation using pip is `pip3 install firectl`, so `pip3` and not `pip`. 

But for Ubuntu/Debian systems you should really install the deb instead:
```
sudo apt update
wget "https://github.com/rahiel/firectl/releases/download/1.0.2/firectl_1.0.2-1_all.deb"
sudo apt install ./firectl_1.0.2-1_all.deb
```

**Comment by breznak** [comment]
hi, 

the problem still remains: 
```
 apt install  ./firectl_1.0.2-1_all.deb
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'firectl' instead of './firectl_1.0.2-1_all.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 firectl : Depends: python3-click but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by rahiel** [comment]
That's weird, could you show me the ouput of `dpkg --get-selections | grep click`?

Normally a combination of `sudo apt-get -f install` and retrying `sudo apt install  ./firectl_1.0.2-1_all.deb` would help.

**Comment by breznak** [comment]
```
pkg --get-selections | grep click
click                                           install
click-apparmor                                  install
gir1.2-click-0.4                                install
libclick-0.4-0:amd64                            install
python3-apparmor-click                          install
python3-click-package                           install
```

> apt install -f

suggests to remove the incomplete package after dpkg, instead of installing it.

**Comment by rahiel** [comment]
Okay, `python3-click-package` conflicts with `python3-click`, this is a mistake Ubuntu made: they chose a python namespace that was already in use.

You'd need to remove that package and the packages that depend on it to continue: `sudo apt remove python3-click-package`

**Comment by breznak** [comment]
I managed to install using that above. 
But there still seems to be some bug in the package: 

```
# firectl
-su: /usr/bin/firectl: /home/rahiel/.virtualenvs/firectl/bin/python3: bad interpreter: No such file or dir
```

**Comment by breznak** [comment]
And there's also broken the removal process: 

```
/var/lib/dpkg/info/firectl.prerm: 6: /var/lib/dpkg/info/firectl.prerm: firectl: not found
dpkg: error processing package firectl (--remove):
 subprocess installed pre-removal script returned error exit status 127
Errors were encountered while processing:
 firectl
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

I'm sorry to bringing so much problems up

**Comment by rahiel** [comment]
Whoops! This one is definitely my fault, I made the deb in a virtualenv, messing up the python path.
Please upgrade:
```
wget "https://github.com/rahiel/firectl/releases/download/1.0.2/firectl_1.0.2-2_all.deb"
sudo apt install ./firectl_1.0.2-2_all.deb
```

Then you can finally use the package, or remove it. Please ask if you encounter more problems.
